### ISSUE TITLE
Transmit that game has been won through Server-sent events when conditions are fulfilled

### ISSUE THREAD

**Issue by na50r** [sopra-fs24-group-41/sopra-fs24-group-41-server#106]

**Comment by Tmmn** [comment]
https://github.com/sopra-fs24-group-41/sopra-fs24-group-41-server/commit/dc14f043f137eda7724011b78545a16ac2925c6b

**Comment by Tmmn** [comment]
https://github.com/sopra-fs24-group-41/sopra-fs24-group-41-server/commit/c9adb5d0230d3820fabccfe198a11556c4a00a5e
