### ISSUE TITLE
implement way the daily goal word gets defined

### ISSUE THREAD

**Issue by Tmmn** [sopra-fs24-group-41/sopra-fs24-group-41-server#170]

**Comment by Aquamarine-12** [comment]
https://github.com/sopra-fs24-group-41/sopra-fs24-group-41-server/commit/882d729e7f59a0e5f3b26646353d531427045f10
https://github.com/sopra-fs24-group-41/sopra-fs24-group-41-server/commit/d743aa0bca50d9d20b82d1263a3a46d1fbf44219

**Comment by Aquamarine-12** [comment]
https://github.com/sopra-fs24-group-41/sopra-fs24-group-41-server/commit/882d729e7f59a0e5f3b26646353d531427045f10
https://github.com/sopra-fs24-group-41/sopra-fs24-group-41-server/commit/d743aa0bca50d9d20b82d1263a3a46d1fbf44219
